# Site settings
title: "Visualization in Data Science (VDS at IEEE VIS 2020)"
email: "vds@ieeevis.org"
description: "Visualization in Data Science (VDS at IEEE VIS 2020)"
baseurl: "/2020"
url: "http://www.visualdatascience.org/"
conferenceshort: "VDS 2020"
conferencedate: "[TBD]"

deadline_submission: "Fri, July 17, 2020"
deadline_notification: "Fri, August 28, 2020"

# Build settings
markdown: kramdown

collections:
- talks

