# Site settings
title: "Visualization in Data Science (VDS at IEEE VIS 2020)"
email: "vds@ieeevis.org"
description: "Visualization in Data Science (VDS at IEEE VIS 2020)"
baseurl: "/2020"
url: "http://www.visualdatascience.org/"
conferenceshort: "VDS 2020"
conferencedate: "Mon, Oct. 26, 2020"

deadline_submission: "<s>Fri, July 17, 2020</s><br> Fri, July 24, 2020"
deadline_notification: "<s>Fri, August 28, 2020</s><br> Fri, Sept. 4, 2020"
event_date: "Mon, Oct. 26, 2020"

# Build settings
markdown: kramdown

collections:
- talks


theme: jekyll-theme-minimal